name: Detect Version Bump
outputs:
  changed:
    description: 'true' if the generator version is bumped
    value: ${{ steps.detection.outputs.changed }}
  version:
    description: New version
    value: ${{ steps.detection.outputs.version }}
runs:
  using: composite
  steps:
    - shell: bash
      id: detection
      run: |
        versionDiff=$( git diff HEAD^ -U0 -- packages/devextreme-angular-generator/package.json )
        if ! [[ $versionDiff ]] || ! [[ $versionDiff =~ (\+ *\"version\":) ]]
        then
          echo "::set-output name=changed::false"
          echo "The generator version is not changed"
          exit 0
        fi

        newVersion=$(echo $versionDiff | grep -oP "\+ *\"version\":.+," | grep -oP "\d+\.\d+.\d+(-beta\.\d+)?")
        echo "The generator version changed to $newVersion"

        echo "::set-output name=changed::true"
        echo "::set-output name=version::$newVersion"
