name: Generator version guard

on:
  push:
    branches:
    - master
    - '[12][0-9].[12]'
  pull_request:

jobs:
  guard:
    runs-on: ubuntu-latest

    steps:
    - name: Get sources
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Run generator version guard
      uses: DevExpress/github-actions/generator-version-guard@main
      with:
        generator_path: packages/devextreme-angular-generator
